function abrirFormulario() {
    window.open("https://forms.gle/Lygktn9FkMvs6i6h8", "_blank")
}

console.log(`
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBMSBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBY       BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBJ      B      BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBu      BBBBBBQ      BBBBBBBBBBBBBBB
BBBBBBBBBBBB1      BBBBBBBBBBBBM      BBBBBBBBBBBB
BBBBBBBBBI      BBBBBBBBBBBBBBBBBBZ      BBBBBBBBB
BBBBBBM      BBBBBBBBBBBBBBBBBBBBBBBBE      BBBBBB
BBBBB7     BBBBBBBBBBBBBBBBBBBBBBBBBBBB      BBBBB
BBBBB        jBBBBBBBBBBBBBBBBBBBBBBB        BBBBB
BBBBB    B      LBBBBBBBBBBBBBBBBB      BB   BBBBB
BBBBB   EBBBB      uBBBBBBBBBBB      BBBBB   BBBBB
BBBBB    BBBBBBB      2BBBBB      BBBBBBBB   BBBBB
BBBBB    BBBBBBBBBB            BBBBBBBBBBB   BBBBB
BBBBB    BBBBBBBBBBBBB      BBBBBBBBBBBBBB   BBBBB
BBBBB    BBBBBBBBBBBBBBB   BBBBBBBBBBBBBBB   BBBBB
BBBBB    BBBBBBBBBBBBBBB   BBBBBBBBBBBBBBB   BBBBB
BBBBB    BBBBBBBBBBBBBBB   BBBBBBBBBBBBBBB   BBBBB
BBBBB   1BBBBBBBBBBBBBBB   BBBBBBBBBBBBBBB   BBBBB
BBBBB    BBBBBBBBBBBBBBB   BBBBBBBBBBBBBBB   BBBBB
BBBBBM    BBBBBBBBBBBBBB   BBBBBBBBBBBBBJ    BBBBB
BBBBBBB      BBBBBBBBBBB   BBBBBBBBBBv      BBBBBB
BBBBBBBBBB      BBBBBBBB   BBBBBBBY      BBBBBBBBB
BBBBBBBBBBBBB      BBBBB   BBBBj      BBBBBBBBBBBB
BBBBBBBBBBBBBBBB      BB   BP      BBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBQ             BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBQ       BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
`);

console.log(`

`);

console.log(`Você é apaixonado por inovação e tecnologia? Quer fazer parte de uma equipe criativa e dinâmica que transforma ideias em soluções digitais incríveis? Junte-se a nós na StarDevs e faça parte da nossa jornada de sucesso! Explore oportunidades emocionantes e traga sua expertise para moldar o futuro da tecnologia. Vamos construir juntos o próximo grande projeto. Candidate-se hoje e seja parte da revolução digital! 🚀💼

Acesse o link: https://forms.gle/ifGyhhMLsQaPrza37
`);